### get all users
GET http://localhost:3000/users

### tìm kiếm theo tên
GET http://localhost:3000/products?name=n

###
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Tivi here",
  "dateofbirh": "2020-01-01",
  "gender": "Nam",
  "email": "hung@gmail.com",
  "phone": 123456,
  "test": "Thi Cau Long tai Sai Gon"
}

###
PUT http://localhost:3000/users/7
Content-Type: application/json

{
  "name": "Minh Hung",
  "dateofbirh": "2020-01-01",
  "gender": "Nu",
  "email": "hung@gmail.com",
  "phone": 123456,
  "test": "Thi boi"
}

###
DELETE http://localhost:3000/users/7













